name: Build blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i --no-fund --no-audit

      - name: Build
        env:
          SITE_URL: https://mohithnovoct.github.io
        run: npm run build

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): build blog (posts, index, sitemap, rss)"
          file_pattern: |
            blog/**
            assets/posts.json
            sitemap.xml
            feed.xml


